package com.mansoor.CRUD;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

 @Entity//: Marks this class as a JPA entity, mapping it to a database table named 'user'.
public class User {

    // @Id: Specifies the primary key of the entity.
    @Id
    // @GeneratedValue: Configures the primary key to be automatically generated by the database.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String email;

    // JPA requires a no-argument constructor for instantiation
    public User() {
    }

    // Constructor for creating new User objects
    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

    // --- Getters and Setters (Accessors and Mutators) ---
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}